import type { BlogPost } from "@/lib/types/blog.types";
import BlogBlockEditor from "../BlogBlockEditor";
import ImageUploadField from "../ImageUploadField";

type Props = { post: BlogPost; onUpdate: <K extends keyof BlogPost>(key: K, value: BlogPost[K]) => void; onTitleChange: (title: string) => void; onSlugChange: (slug: string) => void; onImageUploaded: (path: string, kind: "featured" | "content") => void; onError: (message: string) => void };

export default function BlogDetailsForm({ post, onUpdate, onTitleChange, onSlugChange, onImageUploaded, onError }: Props) {
  return <div className="admin-blog-form-grid">
    <section className="admin-form-section admin-form-section-basics"><div className="admin-form-section-heading"><span>01</span><div><h3>Blog details</h3><p>Set the title, URL, author, and summary.</p></div></div><div className="admin-form-fields"><div className="admin-field admin-field-wide"><label htmlFor="blog-title">Title</label><input id="blog-title" value={post.title} onChange={(event) => onTitleChange(event.target.value)} placeholder="Enter a clear, engaging blog title" /></div><div className="admin-field"><label htmlFor="blog-slug">Slug</label><input id="blog-slug" value={post.slug} onChange={(event) => onSlugChange(event.target.value)} /><small>/blogs/{post.slug || "your-blog-slug"}</small></div><div className="admin-field"><label htmlFor="blog-author">Author</label><input id="blog-author" value={post.author} onChange={(event) => onUpdate("author", event.target.value)} /></div><div className="admin-field"><label htmlFor="blog-category">Category</label><input id="blog-category" value={post.category} onChange={(event) => onUpdate("category", event.target.value)} placeholder="SAP, Analytics, Technology…" /></div><div className="admin-field"><label htmlFor="blog-tags">Tags</label><input id="blog-tags" value={post.tags.join(", ")} onChange={(event) => onUpdate("tags", event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean))} /><small>Separate tags with commas.</small></div><div className="admin-field admin-field-wide"><label htmlFor="blog-description">Short description</label><textarea id="blog-description" rows={3} value={post.shortDescription} onChange={(event) => onUpdate("shortDescription", event.target.value)} placeholder="A short introduction used on blog cards and search results" /></div></div></section>
    <section className="admin-form-section"><div className="admin-form-section-heading"><span>02</span><div><h3>Featured image</h3><p>Upload and control the main image displayed above the article.</p></div></div><div className="admin-form-fields"><div className="admin-field admin-field-wide"><ImageUploadField id="blog-featured-upload" label="Featured image" value={post.featuredImage} alt={post.imageAlt} onUploaded={(path) => { onUpdate("featuredImage", path); onImageUploaded(path, "featured"); }} onError={onError}/></div><div className="admin-field admin-field-wide"><label htmlFor="blog-featured-url">Image URL</label><input id="blog-featured-url" value={post.featuredImage} onChange={(event) => onUpdate("featuredImage", event.target.value)} /></div><div className="admin-field admin-field-wide"><label htmlFor="blog-image-alt">Alternative text</label><input id="blog-image-alt" value={post.imageAlt} onChange={(event) => onUpdate("imageAlt", event.target.value)} /></div><div className="admin-field admin-field-wide admin-featured-style"><label>Image styling</label><div className="admin-featured-style-grid"><StyleSelect label="Width" value={post.featuredImageStyle.width} values={[["50","50%"],["75","75%"],["100","100%"]]} onChange={(value) => onUpdate("featuredImageStyle", { ...post.featuredImageStyle, width: value as BlogPost["featuredImageStyle"]["width"] })}/><StyleSelect label="Alignment" value={post.featuredImageStyle.align} values={[["left","Left"],["center","Center"],["right","Right"]]} onChange={(value) => onUpdate("featuredImageStyle", { ...post.featuredImageStyle, align: value as BlogPost["featuredImageStyle"]["align"] })}/><StyleSelect label="Maximum height" value={post.featuredImageStyle.maxHeight} values={[["320","320px"],["480","480px"],["640","640px"],["auto","Automatic"]]} onChange={(value) => onUpdate("featuredImageStyle", { ...post.featuredImageStyle, maxHeight: value as BlogPost["featuredImageStyle"]["maxHeight"] })}/><StyleSelect label="Image fit" value={post.featuredImageStyle.objectFit} values={[["contain","Show complete image"],["cover","Fill available area"]]} onChange={(value) => onUpdate("featuredImageStyle", { ...post.featuredImageStyle, objectFit: value as BlogPost["featuredImageStyle"]["objectFit"] })}/><StyleSelect label="Corners" value={post.featuredImageStyle.borderRadius} values={[["0","Square"],["8","Small"],["16","Medium"],["24","Large"]]} onChange={(value) => onUpdate("featuredImageStyle", { ...post.featuredImageStyle, borderRadius: value as BlogPost["featuredImageStyle"]["borderRadius"] })}/></div></div></div></section>
    <section className="admin-form-section admin-form-section-content"><div className="admin-form-section-heading"><span>03</span><div><h3>Build the article</h3><p>Drag blocks into place, style them, and review the live page.</p></div></div><BlogBlockEditor blocks={post.contentBlocks} title={post.title} description={post.shortDescription} featuredImage={post.featuredImage} featuredImageStyle={post.featuredImageStyle} onChange={(blocks) => onUpdate("contentBlocks", blocks)} onImageUploaded={(path) => onImageUploaded(path, "content")} onError={onError}/></section>
    <section className="admin-form-section"><div className="admin-form-section-heading"><span>04</span><div><h3>Search visibility</h3><p>Control how the blog appears in search results.</p></div></div><div className="admin-form-fields"><div className="admin-field"><label htmlFor="blog-seo-title">SEO title</label><input id="blog-seo-title" value={post.seoTitle} onChange={(event) => onUpdate("seoTitle", event.target.value)} /></div><div className="admin-field"><label htmlFor="blog-seo-description">SEO description</label><textarea id="blog-seo-description" rows={4} value={post.seoDescription} onChange={(event) => onUpdate("seoDescription", event.target.value)} /></div></div></section>
  </div>;
}

function StyleSelect({ label, value, values, onChange }: { label: string; value: string; values: string[][]; onChange: (value: string) => void }) { return <div><label>{label}</label><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map(([optionValue, text]) => <option value={optionValue} key={optionValue}>{text}</option>)}</select></div>; }
